task:
  box_width: 2.2
  box_height: 2.2
  border_region: 0.03
  border_slow_factor: 0.25
  init_pos: "uniform"
  biased: false
  drift_const: 0.05
  anchor_point: [0, 0]
  dt: 0.02
  mu: 0
  sigma: 11.52
  b: ${eval:${pi:} * 0.26}
  use_place_cells: true
  place_cells_num: 512
  place_cells_sigma: 0.2
  place_cells_dog: false
  place_cells_surround_scale: 2
  sequence_length: 100
  batch_size: 200
