task:
  init_hd: "uniform"
  biased: false
  dt: 0.02
  mu: 0
  sigma: 11.52
  use_hd_cells: true
  hd_cells_num: 512
  hd_cells_angular_spread: ${eval:${pi:}/6}
  sequence_length: 100
  batch_size: 200
rnn:
  n_in: 1
  n_rec: 128
  n_out: 512
  n_init: 512
  dt: 0.5
trainer:
  n_epochs: 20000
